#
# DO NOT EDIT THIS FILE
# 
# Set variables in `config/*.config.sh`
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. >/dev/null 2>&1 && pwd )"

# General configuration
if [ ! -f $DIR/config/machine.config.sh ] ; then
    echo "No machine configuration file found"
    echo "Create $DIR/config/machine.config.sh before continuing"
    exit 1
fi

source $DIR/config/machine.config.sh

# Platform-specific configuration
if [ ! -f $DIR/config/$BUILD_TYPE.config.sh ] ; then
    echo "No machine configuration file found"
    echo "Create $DIR/config/$BUILD_TYPE.config.sh before continuing"
    exit 1
fi

source $DIR/config/$BUILD_TYPE.config.sh
